"""
MITS Data Schemas

Pydantic models for all data structures in the ITS.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime
import uuid


# ═══════════════════════════════════════════════════════════════════════════
# ENUMS
# ═══════════════════════════════════════════════════════════════════════════

class Difficulty(str, Enum):
    """Task difficulty levels."""
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    OLYMPIAD = "olympiad"


class Subject(str, Enum):
    """Subject areas."""
    MATH = "math"
    PROGRAMMING = "programming"


class TutorMove(str, Enum):
    """Types of tutor responses (teaching moves)."""
    SCAFFOLDING = "scaffolding"      # Break into steps, guide
    PROBLEMATIZE = "problematize"    # Ask why/what if
    RECTIFY = "rectify"              # Point out errors
    ENCOURAGE = "encourage"          # Celebrate progress
    HINT = "hint"                    # Give subtle hint
    TELL = "tell"                    # Reveal answer (last resort!)


# ═══════════════════════════════════════════════════════════════════════════
# TASK MODELS
# ═══════════════════════════════════════════════════════════════════════════

class Task(BaseModel):
    """A mathematical or programming task."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    subject: Subject = Subject.MATH
    topic: str
    subtopic: Optional[str] = None
    difficulty: Difficulty = Difficulty.MEDIUM
    skills: List[str] = Field(default_factory=list)
    
    # Content
    problem: str
    solution: str
    answer: str
    
    # Teaching aids
    hints: List[str] = Field(default_factory=list, max_length=3)
    common_mistakes: List[str] = Field(default_factory=list)
    
    # Metadata
    estimated_time_minutes: int = 10
    created_at: datetime = Field(default_factory=datetime.now)
    
    class Config:
        json_schema_extra = {
            "example": {
                "topic": "derivatives",
                "difficulty": "medium",
                "problem": "Find the derivative of f(x) = x²sin(x)",
                "solution": "Using product rule...",
                "answer": "2x·sin(x) + x²·cos(x)",
                "hints": ["What rule applies to products?", "Remember: (uv)' = u'v + uv'"],
                "skills": ["product_rule", "chain_rule"]
            }
        }


# ═══════════════════════════════════════════════════════════════════════════
# CONVERSATION MODELS
# ═══════════════════════════════════════════════════════════════════════════

class ConversationTurn(BaseModel):
    """A single turn in the tutoring conversation."""
    
    role: str  # "student" or "tutor"
    content: str
    move: Optional[TutorMove] = None  # Only for tutor turns
    timestamp: datetime = Field(default_factory=datetime.now)
    
    @property
    def is_tutor(self) -> bool:
        return self.role == "tutor"


class TutorResponse(BaseModel):
    """Response generated by the tutor agent."""
    
    move: TutorMove
    message: str
    internal_reasoning: Optional[str] = None  # Chain-of-thought (hidden)
    hint_number: Optional[int] = None
    is_telling: bool = False  # ⚠️ Track if we gave away the answer
    
    @property
    def is_socratic(self) -> bool:
        """Check if response follows Socratic method."""
        return self.move in [TutorMove.SCAFFOLDING, TutorMove.PROBLEMATIZE]


# ═══════════════════════════════════════════════════════════════════════════
# SESSION MODELS
# ═══════════════════════════════════════════════════════════════════════════

class TutoringSession(BaseModel):
    """A complete tutoring session for one task."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    student_id: str
    task: Task
    
    # Conversation history
    conversation: List[ConversationTurn] = Field(default_factory=list)
    
    # Progress tracking
    hints_used: int = 0
    attempts: int = 0
    
    # Outcome
    is_solved: bool = False
    told_answer: bool = False  # ⚠️ Penalized in metrics!
    
    # Timestamps
    started_at: datetime = Field(default_factory=datetime.now)
    ended_at: Optional[datetime] = None
    
    def add_student_message(self, content: str) -> None:
        """Add a student message to conversation."""
        self.conversation.append(
            ConversationTurn(role="student", content=content)
        )
        self.attempts += 1
    
    def add_tutor_response(self, response: TutorResponse) -> None:
        """Add a tutor response to conversation."""
        self.conversation.append(
            ConversationTurn(
                role="tutor",
                content=response.message,
                move=response.move
            )
        )
        if response.move == TutorMove.HINT:
            self.hints_used += 1
        if response.is_telling:
            self.told_answer = True


# ═══════════════════════════════════════════════════════════════════════════
# STUDENT MODELS
# ═══════════════════════════════════════════════════════════════════════════

class StudentProfile(BaseModel):
    """Student profile with learning history."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: Optional[str] = None
    
    # Knowledge State
    topic_mastery: Dict[str, float] = Field(default_factory=dict)
    skill_mastery: Dict[str, float] = Field(default_factory=dict)
    
    # Learning History
    tasks_attempted: int = 0
    tasks_solved: int = 0
    total_hints_used: int = 0
    
    # Preferences
    preferred_difficulty: Difficulty = Difficulty.MEDIUM
    learning_style: str = "step_by_step"  # visual, examples, step_by_step
    
    # Session State
    current_streak: int = 0
    last_active: datetime = Field(default_factory=datetime.now)
    
    @property
    def success_rate(self) -> float:
        """Calculate overall success rate."""
        if self.tasks_attempted == 0:
            return 0.0
        return self.tasks_solved / self.tasks_attempted
    
    def get_weak_skills(self, threshold: float = 0.5) -> List[str]:
        """Get skills below mastery threshold."""
        return [
            skill for skill, mastery in self.skill_mastery.items()
            if mastery < threshold
        ]


# ═══════════════════════════════════════════════════════════════════════════
# VERIFICATION MODELS
# ═══════════════════════════════════════════════════════════════════════════

class VerificationResult(BaseModel):
    """Result of verifying a student's answer."""
    
    is_correct: bool
    is_partial: bool = False  # Partially correct
    confidence: float = 1.0   # Confidence in verification
    
    # Error analysis
    has_error: bool = False
    error_type: Optional[str] = None  # "arithmetic", "conceptual", "notation"
    error_location: Optional[str] = None
    
    # Feedback
    feedback: Optional[str] = None
